//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManDataEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAILYON
    {
        public decimal SYSTEMDATE { get; set; }
        public string SYSTEMTIME { get; set; }
        public string COMPANYCD { get; set; }
        public string EMPLOYECD { get; set; }
        public string LOGINUSER { get; set; }
        public string APPROVEUSER { get; set; }
        public string APPROVEYN { get; set; }
        public string PAYYYYYMM { get; set; }
        public decimal DUTYDATE { get; set; }
        public string BEGINTIME { get; set; }
        public string ENDTIME { get; set; }
        public string OVERONWORK { get; set; }
        public string OVEROFFWORK { get; set; }
        public decimal OVERWORK1 { get; set; }
        public decimal OVERWORK2 { get; set; }
        public decimal OVERWORK3 { get; set; }
        public decimal OVERWORK4 { get; set; }
        public decimal OVERWORK5 { get; set; }
        public decimal OVERWORKHOURS { get; set; }
        public decimal WORKHOURS { get; set; }
        public decimal WORKDAYS { get; set; }
        public string HOLIDAY { get; set; }
        public string WORKTYPE { get; set; }
        public string SEQNOX { get; set; }
        public string POSTEDYN { get; set; }
        public string REMARK { get; set; }
        public string RESTYN { get; set; }
        public decimal ADDHOURS { get; set; }
        public decimal CHANGEDATE { get; set; }
        public decimal MEALDELAY { get; set; }
        public string UnitCd { get; set; }
        public string CostCd { get; set; }
        public decimal FixedPay18 { get; set; }
        public decimal FixedPay19 { get; set; }
        public decimal FixedPay20 { get; set; }
        public decimal FixedPay21 { get; set; }
        public decimal FixedPay22 { get; set; }
        public decimal OffHours { get; set; }
        public decimal LOffDate { get; set; }
        public decimal MEALDELAY2 { get; set; }
        public decimal FORMID { get; set; }
        public decimal ROWID { get; set; }
        public decimal H_TYPE { get; set; }
    }
}
