//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManDataEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAILYONOFF
    {
        public decimal SYSTEMDATE { get; set; }
        public string SYSTEMTIME { get; set; }
        public string COMPANYCD { get; set; }
        public string EMPLOYECD { get; set; }
        public string LOGINUSER { get; set; }
        public string APPROVEUSER { get; set; }
        public string APPROVEYN { get; set; }
        public string POSTEDYN { get; set; }
        public decimal DUTYDATE { get; set; }
        public string SEQNOX { get; set; }
        public string BEGINTIME { get; set; }
        public string ENDTIME { get; set; }
        public string PAYYYYYMM { get; set; }
        public decimal OVERWORK1 { get; set; }
        public decimal OVERWORK2 { get; set; }
        public decimal OVERWORK3 { get; set; }
        public decimal OVERWORK4 { get; set; }
        public decimal OVERWORK5 { get; set; }
        public decimal RECREATEDAYS { get; set; }
        public decimal WORKHOURS { get; set; }
        public decimal WORKDAYS { get; set; }
        public decimal OFFWORK1 { get; set; }
        public decimal OFFWORK2 { get; set; }
        public decimal OFFWORK3 { get; set; }
        public decimal OFFWORK4 { get; set; }
        public decimal OFFWORK5 { get; set; }
        public decimal OFFWORK6 { get; set; }
        public decimal OFFWORK7 { get; set; }
        public decimal OFFWORK8 { get; set; }
        public decimal OFFWORK9 { get; set; }
        public decimal OFFWORK10 { get; set; }
        public string OVERONWORK { get; set; }
        public string OVEROFFWORK { get; set; }
        public decimal OFFWORK5M { get; set; }
        public decimal OFFWORK6M { get; set; }
        public string ERRORYN { get; set; }
        public string WORKTYPE { get; set; }
        public string HOLIDAY { get; set; }
        public decimal OFFHOURS { get; set; }
        public decimal ADDHOURS { get; set; }
        public decimal OVERWORKHOURS { get; set; }
        public decimal MEALDELAY { get; set; }
        public decimal OFFWORK11 { get; set; }
        public decimal OFFWORK12 { get; set; }
        public decimal OFFWORKHOURS { get; set; }
        public decimal TAXHOURS { get; set; }
        public string NEXTDAYYN { get; set; }
        public string MARK { get; set; }
        public string RESTYN { get; set; }
        public string BreakOn { get; set; }
        public string BreakOff { get; set; }
        public decimal LOSTTIMES { get; set; }
        public string RemarkOn { get; set; }
        public string RemarkOff { get; set; }
        public string LeaveTimeBeg { get; set; }
        public string LeaveTimeEnd { get; set; }
        public decimal FixedPay18 { get; set; }
        public decimal FixedPay19 { get; set; }
        public decimal FixedPay20 { get; set; }
        public decimal FixedPay21 { get; set; }
        public decimal FixedPay22 { get; set; }
        public string UNITCD { get; set; }
        public string COSTCD { get; set; }
        public decimal RealOnDate { get; set; }
        public decimal RealOffDate { get; set; }
        public decimal OffWork14 { get; set; }
        public decimal OffWork15 { get; set; }
        public decimal OFFWORK16 { get; set; }
        public decimal OFFWORK17 { get; set; }
        public decimal OFFWORK18 { get; set; }
        public decimal OFFWORK19 { get; set; }
        public decimal FLAG { get; set; }
        public Nullable<decimal> H_TYPE { get; set; }
    }
}
