//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManDataEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAILYOFF
    {
        public decimal SYSTEMDATE { get; set; }
        public string SYSTEMTIME { get; set; }
        public string COMPANYCD { get; set; }
        public string EMPLOYECD { get; set; }
        public string LOGINUSER { get; set; }
        public string APPROVEUSER { get; set; }
        public string APPROVEYN { get; set; }
        public string PAYYYYYMM { get; set; }
        public decimal DUTYDATE { get; set; }
        public string BEGINTIME { get; set; }
        public string ENDTIME { get; set; }
        public decimal OFFWORK1 { get; set; }
        public decimal OFFWORK2 { get; set; }
        public decimal OFFWORK3 { get; set; }
        public decimal OFFWORK4 { get; set; }
        public decimal OFFWORK5 { get; set; }
        public decimal OFFWORK6 { get; set; }
        public decimal OFFWORK7 { get; set; }
        public decimal OFFWORK8 { get; set; }
        public decimal OFFWORK9 { get; set; }
        public decimal OFFWORK10 { get; set; }
        public decimal OFFWORK11 { get; set; }
        public decimal OFFWORK12 { get; set; }
        public decimal OFFWORKHOURS { get; set; }
        public decimal OFFWORK5M { get; set; }
        public decimal OFFWORK6M { get; set; }
        public string WORKTYPE { get; set; }
        public string SEQNOX { get; set; }
        public string POSTEDYN { get; set; }
        public string REMARK { get; set; }
        public string RESTYN { get; set; }
        public decimal RECREATEHOURS { get; set; }
        public decimal CHANGEDATE { get; set; }
        public decimal RECREATEDAYS { get; set; }
        public decimal OFFHOURS { get; set; }
        public string LeaveTimeBeg { get; set; }
        public string LeaveTimeEnd { get; set; }
        public decimal OffWork14 { get; set; }
        public decimal OffWork15 { get; set; }
        public decimal FORMID { get; set; }
        public decimal ROWID { get; set; }
        public decimal OFFWORK16 { get; set; }
        public decimal OFFWORK17 { get; set; }
        public decimal OFFWORK18 { get; set; }
        public decimal OFFWORK19 { get; set; }
        public Nullable<decimal> CodeIndex { get; set; }
        public string DorH { get; set; }
    }
}
