//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManDataEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUTYWORK
    {
        public string COMPANYCD { get; set; }
        public string EMPLOYECD { get; set; }
        public string WORKYYYYMM { get; set; }
        public decimal WORKDATE { get; set; }
        public string WORKTYPE { get; set; }
        public string HALFDAY { get; set; }
        public string AutoInfo { get; set; }
        public string Subject { get; set; }
        public string HOLIDAY { get; set; }
        public decimal WORKHOURS { get; set; }
        public decimal JOBHOURS { get; set; }
        public decimal ADDHOURS { get; set; }
        public decimal OFFHOURS { get; set; }
        public decimal WorkDays { get; set; }
        public decimal rowid { get; set; }
        public string CardNo { get; set; }
        public decimal RosterAmt { get; set; }
        public decimal CarAllowAmt { get; set; }
        public decimal MealAllowAmt { get; set; }
        public string PayYYYYMM { get; set; }
        public decimal WorkDateEnd { get; set; }
        public decimal H_TYPE { get; set; }
        public string LEAVECD { get; set; }
        public decimal SYSTEMDATE { get; set; }
        public string SYSTEMTIME { get; set; }
        public string LOGINUSER { get; set; }
    }
}
