//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManDataEntities.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRISDB : DbContext
    {
        public HRISDB()
            : base("name=HRISDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DUTYWORK> DUTYWORK { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<WORKTIME> WORKTIME { get; set; }
        public virtual DbSet<DAILYOFF> DAILYOFF { get; set; }
        public virtual DbSet<DAILYON> DAILYON { get; set; }
        public virtual DbSet<DAILYONOFF> DAILYONOFF { get; set; }
        public virtual DbSet<LOSTCARD> LOSTCARD { get; set; }
    }
}
