//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManDataEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string COMPANYCD { get; set; }
        public string EMPLOYECD { get; set; }
        public string DEPARTCD { get; set; }
        public string UNITCD { get; set; }
        public string COSTTYPE { get; set; }
        public string HIRETYPE { get; set; }
        public string CHINESENAME { get; set; }
        public string ENGLISHNAME { get; set; }
        public string TITLECD { get; set; }
        public string TITLEGD { get; set; }
        public string JOBFAMILY { get; set; }
        public string TECHCD { get; set; }
        public string INCOMECD { get; set; }
        public string PASSYN { get; set; }
        public string EDUCATEGD { get; set; }
        public string GRADSCHOOL { get; set; }
        public string GRADDEPART { get; set; }
        public decimal GRADYEAR { get; set; }
        public string WORKPLACE { get; set; }
        public string WORKTYPE { get; set; }
        public string NATIONCD { get; set; }
        public string LICENSECD { get; set; }
        public string MILITARY { get; set; }
        public string CARDNO { get; set; }
        public string SEXTYPE { get; set; }
        public string BLOODTYPE { get; set; }
        public string IDNUMBER { get; set; }
        public string IDCHECK { get; set; }
        public string MARRIAGE { get; set; }
        public decimal BIRTHDAY { get; set; }
        public string PASSPORT { get; set; }
        public string URGENTTO { get; set; }
        public string URGENTTELNO { get; set; }
        public string RELATIONSHIP { get; set; }
        public string HOMEADDRESS { get; set; }
        public string TEMPADDRESS { get; set; }
        public string HOMETELNO { get; set; }
        public string TEMPTELNO { get; set; }
        public string CELLULARNO { get; set; }
        public string BIBICALL { get; set; }
        public string BANKACCOUNT { get; set; }
        public decimal TAXMANS { get; set; }
        public decimal HEALTHMANS { get; set; }
        public decimal LABORDATE { get; set; }
        public decimal LABORAMOUNT { get; set; }
        public decimal HEALTHDATE { get; set; }
        public decimal HEALTHAMOUNT { get; set; }
        public string GROUPYN { get; set; }
        public string ACCIDENTYN { get; set; }
        public string MOTORHLYN { get; set; }
        public string CARYN { get; set; }
        public string MOTORMM { get; set; }
        public string CARMM { get; set; }
        public string OTHERINSYN { get; set; }
        public string OTHERDEDYN { get; set; }
        public string ADDYN { get; set; }
        public string OFFYN { get; set; }
        public decimal BASICPAY { get; set; }
        public string JOBSTATUS { get; set; }
        public decimal FULLMONTH { get; set; }
        public string FULLTYPE { get; set; }
        public decimal HIREDATE { get; set; }
        public decimal ENDDATE { get; set; }
        public decimal QUITDATE { get; set; }
        public decimal REHIREDATE { get; set; }
        public decimal OFFJOBBEG { get; set; }
        public decimal OFFJOBEND { get; set; }
        public string MEALYN { get; set; }
        public string BODYSTATUS { get; set; }
        public decimal MAXADDPAY { get; set; }
        public decimal WORKHOURS { get; set; }
        public decimal INHOUSEDAYS { get; set; }
        public decimal QUITDAYS { get; set; }
        public decimal OUTDOORDAYS { get; set; }
        public decimal ADDDAYS { get; set; }
        public decimal RECREATEDAYS { get; set; }
        public decimal INCREASEDAYS { get; set; }
        public decimal USEDDAYS { get; set; }
        public string REGIONCD { get; set; }
        public decimal LASTFMONTH { get; set; }
        public decimal UNUSEDDAYS { get; set; }
        public decimal CUTOFFDATE { get; set; }
        public string POSTYN { get; set; }
        public decimal ADDOFFHOURS { get; set; }
        public string BANKCD { get; set; }
        public string DEPARTCDOLD { get; set; }
        public string UNITCDOLD { get; set; }
        public string REGIONCDOLD { get; set; }
        public string GROUPCD { get; set; }
        public string EMAILADDRESS { get; set; }
        public decimal SEQUENTIALNO { get; set; }
        public decimal ENDLABORDATE { get; set; }
        public decimal ENDHEALTHDATE { get; set; }
        public decimal UPGRADEDATE { get; set; }
        public decimal LASTYEARDAYS { get; set; }
        public decimal WORKRATEC1 { get; set; }
        public decimal WORKRATEM1 { get; set; }
        public decimal WORKRATEC2 { get; set; }
        public decimal WORKRATEM2 { get; set; }
        public decimal WORKRATEC3 { get; set; }
        public decimal WORKRATEM3 { get; set; }
        public decimal WORKRATEC4 { get; set; }
        public decimal WORKRATEM4 { get; set; }
        public string RESTTYPE { get; set; }
        public string DIRECTBOSS { get; set; }
        public decimal WORKRATEC5 { get; set; }
        public decimal WORKRATEM5 { get; set; }
        public decimal OFFWRATEC1 { get; set; }
        public decimal OFFWRATEM1 { get; set; }
        public decimal OFFWRATEC2 { get; set; }
        public decimal OFFWRATEM2 { get; set; }
        public decimal OFFWRATEC3 { get; set; }
        public decimal OFFWRATEM3 { get; set; }
        public decimal GroupMans { get; set; }
        public string BANKCD2 { get; set; }
        public string CardYN { get; set; }
        public string ToYouWish { get; set; }
        public string BANKACCOUNT2 { get; set; }
        public string Currency { get; set; }
        public string PassWord { get; set; }
        public string ISBoss { get; set; }
        public string BossLevel { get; set; }
        public string CostCenter { get; set; }
        public string SendMail { get; set; }
        public decimal JoinNewDate { get; set; }
        public decimal QuitNewDate { get; set; }
        public string FundAccrueYn { get; set; }
        public decimal FundBase { get; set; }
        public decimal FundRateEmp { get; set; }
        public decimal FundRateCmp { get; set; }
        public decimal PayOffWork1 { get; set; }
        public decimal PayOffWork2 { get; set; }
        public string FundType { get; set; }
        public string ResidenceNo { get; set; }
        public string TaxNo { get; set; }
        public string BankIDNo { get; set; }
        public Nullable<decimal> ComeInDate { get; set; }
        public Nullable<decimal> OutDate { get; set; }
        public decimal taxrate { get; set; }
        public string NHINS2YN { get; set; }
        public string Language { get; set; }
        public decimal ObliUp { get; set; }
        public decimal ObliDn { get; set; }
        public decimal INCENTIVERATE { get; set; }
    }
}
