//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManDataEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOSTCARD
    {
        public string CARDNO { get; set; }
        public decimal CARDDATE { get; set; }
        public string CARDTIME { get; set; }
        public string CARDTYPE { get; set; }
        public decimal FLAG { get; set; }
        public decimal ROWID { get; set; }
        public string Sequenceid { get; set; }
    }
}
