//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManDataEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKTIME
    {
        public string COMPANYCD { get; set; }
        public string WORKTYPE { get; set; }
        public string WORKONSAT { get; set; }
        public string MORNINGTIME { get; set; }
        public string MAXMORNINGTIME { get; set; }
        public string NEXTDAYYN { get; set; }
        public string OFFWORKTIME { get; set; }
        public string DELAYTIME { get; set; }
        public decimal DELAYHOUR { get; set; }
        public string NOONTIME { get; set; }
        public decimal NOONHOUR { get; set; }
        public string ADDWORKTIME { get; set; }
        public string OVERWORKTIME { get; set; }
        public string afternoontime { get; set; }
        public string finalofftime { get; set; }
        public decimal WORKHOURSM { get; set; }
        public decimal WORKHOURSD { get; set; }
        public decimal RECORDTIMES { get; set; }
        public decimal ROSTERAMT { get; set; }
        public decimal RosterHrs { get; set; }
        public string NoonTime2 { get; set; }
        public decimal NoonHour2 { get; set; }
        public string NoonTime3 { get; set; }
        public decimal NoonHour3 { get; set; }
        public string NoonTime4 { get; set; }
        public decimal NoonHour4 { get; set; }
        public string NoonTime5 { get; set; }
        public decimal NoonHour5 { get; set; }
        public decimal SysAuto { get; set; }
    }
}
